Milestone 3: Interactive form
mbabaliiryn/react-book-store pull request #3
Opened 2020-09-22 08:31 UTC by mbabaliiryn

## Make form interactive
- Make the BooksForm component Stateful
- Connect the remove book action to the component
- Update readme file

2020-09-22 09:12 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

* [ ] The `BookList` component should implement `handleBookRemove` which is then passed as props to the `Book` component. [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png)

- [x] Let's fix the linter errors as well.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-22 09:12 UTC, suretrust commented on src/containers/BooksList.js
> +/* eslint-disable no-unused-vars */
Remove any variable or import that you aren't using, no need to disable the rule

2020-09-22 09:12 UTC, suretrust commented on src/components/Book.js
> +const Book = ({ book, removeBook }) => (
```suggestion
const Book = ({ book, handleBookRemove }) => (
```

2020-09-22 09:12 UTC, suretrust commented on src/components/Book.js
> +      <button type="button" onClick={() => removeBook(book.id)}>x</button>
```suggestion
      <button type="button" onClick={handleBookRemove}>x</button>
```

2020-09-22 09:12 UTC, suretrust commented on src/containers/BooksList.js
> +const BooksList = ({ books, removeBook }) => {
```suggestion
const BooksList = ({ books, removeBook }) => {
   const handleBookRemove = (book) => removeBook(book)
```

2020-09-22 09:12 UTC, suretrust commented on src/containers/BooksList.js
> +            <Book key={book.id} book={book} removeBook={removeBook} />
```suggestion
            <Book key={book.id} book={book} handleBookRemove={handleBookRemove} />
```

2020-09-22 09:35 UTC, imahnama commented on src/containers/BooksList.js
> +/* eslint-disable no-unused-vars */
noted

2020-09-22 15:58 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [x] The suggestion was not about the naming of the variables, please check through the previous code review as well as the new one below to better understand the suggestion.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-09-22 15:58 UTC, suretrust commented on src/actions/index.js
> +export const handleBookRemove = id => ({
This should remain `removeBook`.
```suggestion
export const removeBook = id => ({
```

2020-09-22 15:58 UTC, suretrust commented on src/containers/BooksList.js
> +const BooksList = ({ books, handleBookRemove }) => {
**Implement `handleBookRemove` here.** `BooksList` should accept `removeBook` as props, then inside the component, implement the `handleBookRemove`, which looks similar to the code below. Finally, pass `handleBookRemove` as props to the `Book` component.

```javascript
const handleBookRemove = (book) => removeBook(book)
```

2020-09-23 10:09 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @mbabaliiryn @imahnama this looks good to me, you have done well so far please merge and move on this is approved :+1:  

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-23 11:32 UTC, merged